[package]
name = "crank"
version = "0.1.0"
authors = ["Raas Ahsan"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.68"
parcel = { git = "https://github.com/ncatelli/parcel", tag = "v1.6.0" }